version: '3.8'

services:
  backend:
    build: .
    container_name: backend_calorias
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
